-- Create technical_signals table for Alpha Zoo output
create table if not exists public.technical_signals (
    id bigint generated by default as identity primary key,
    ticker text not null unique,
    score integer,
    alpha_zoo_score integer,
    alpha_factor_count integer,
    mean_reversion_signals text[],
    computed_at timestamptz default now()
);

-- Enable RLS
alter table public.technical_signals enable row level security;
create policy "Allow all" on public.technical_signals for all using (true) with check (true);

-- Create sector_momentum table
create table if not exists public.sector_momentum (
    id bigint generated by default as identity primary key,
    sector text not null unique,
    avg_grade numeric,
    avg_return_1d numeric,
    avg_return_5d numeric,
    avg_return_20d numeric,
    momentum_score integer,
    top_tickers text[],
    buy_count integer,
    hold_count integer,
    sell_count integer,
    computed_at timestamptz default now()
);

alter table public.sector_momentum enable row level security;
create policy "Allow all" on public.sector_momentum for all using (true) with check (true);

-- Create macro_signals table
create table if not exists public.macro_signals (
    id bigint generated by default as identity primary key,
    signal_name text not null unique,
    signal_value numeric,
    signal_direction text,
    impact_sector text,
    confidence integer,
    source text,
    computed_at timestamptz default now()
);

alter table public.macro_signals enable row level security;
create policy "Allow all" on public.macro_signals for all using (true) with check (true);

-- Create weather_patterns table
create table if not exists public.weather_patterns (
    id bigint generated by default as identity primary key,
    region text,
    pattern_type text,
    severity integer,
    affected_sectors text[],
    affected_tickers text[],
    start_date text,
    end_date text,
    computed_at timestamptz default now()
);

alter table public.weather_patterns enable row level security;
create policy "Allow all" on public.weather_patterns for all using (true) with check (true);
